### ISSUE TITLE
No callback on error sending push token 

### ISSUE THREAD

**Issue by EvgeniyaKonobeeva** [exponea/exponea-android-sdk#25]
I try to send push token to Exponea by calling 
Exponea.trackPushToken(token)
but I can't know if it is really delivered successfully. Threre is no callback for this.
So now some users haven't push token in exponea, I forced to spam with push token to Exponea in every session.

**Comment by wassil** [comment]
Tracking works in 2 steps. First, we add event into an internal database. Second, based on flush setup(immediate/manual/periodic/appclose) we send the event to the server. Flushing only runs when there is internet connection, there are 5 retries in case of server outage/other error.

**Comment by wassil** [comment]
Tracking works in 2 steps. First, we add event into an internal database. Second, based on flush setup(immediate/manual/periodic/appclose) we send the event to the server. Flushing only runs when there is internet connection, there are 5 retries in case of server outage/other error.

Because there can be a long time between tracking an event and the event being stored on Exponea servers, it's basically impossible to provide a callback for this.

Have you considered automatic push notification tracking? It handles token tracking for you.
