### ISSUE TITLE
notificationDataCallback 

### ISSUE THREAD

**Issue by KasalaRoman** [exponea/exponea-android-sdk#37]
Hello,

Does [this ](https://github.com/exponea/exponea-android-sdk/blob/develop/Documentation/PUSH.md#handling-notification-payload-extra-data) feature 

Exponea.notificationDataCallback = {
     extra -> //handle the extras value
}

works correctly ?
It is triggered with every delievered PUSH, and not only with the ones that contains "Additional Data" / extra data, bcs it contains always basic information sent in campaign events like campaign_name, action_type etc.

And also, if i send extra data with same name as those basic information e.g. action_type it is ignored

**Comment by michaela-dev** [comment]
Hi, sorry for the (very) late reply. Yes, this is how this callback currently works. Since the campaign always sends some extra data, the callback is always called. Some attribute names are reserved for standard attributes sent by the Exponea itself, so they can not be overridden. If you have any more questions or ideas on how to improve SDK, let us know. Closing this issue for now.
