### ISSUE TITLE
remove HashMap from PropertiesList public api

### ISSUE THREAD

**Issue by ursusursus** [exponea/exponea-android-sdk#45]
Hi, could the PropertiesList please take Map instead of HashMap to be more kotlin idiomatic?

**Comment by adam1929** [comment]
Sorry @ursusursus API is already defined and we are not able to change it -- technically speaking it is possible and it is easy, but unfortunately it will hit all existing customers :-/

**Comment by ursusursus** [comment]
how so? if hashmap extends map, then all callsites should work even if library changes api to map, no?

**Comment by adam1929** [comment]
No, this is opposite.
Hashmap extends from Map AND MutableMap. So you may put items to hashmap at any time and that instance will be updated (technically speaking Hashmap has 'set' operator).
Map is "only" map. So you are unable to put items to existing instance, you'll get a new 'map' instance but a original one will not be updated (has only 'plus' operator).
So from this, you may imagine a case that developer will create a `var props = PropertiesList(data)` and then he'll put items into 'data' rather than 'props'. His result will have same result. If we change it to 'Map', he'll get a compilation error.
But back to original question -> you are right that Map has to be used in these cases, with no doubt. But we already release it as part of SDK API and we are unable to change it because it will hit all existing developers and it forces them to reimplement their part of code (potentially).
