### ISSUE TITLE
Manifest conflicts

### ISSUE THREAD

**Issue by PeterCvopa** [exponea/exponea-android-sdk#49]
When updated from version 3.0.4 to 3.1.0 experiencing merger manifest issue
(Manifest merger failed : Attribute application@fullBackupContent value=(@xml/old_backup_rules) from AndroidManifest.xml:38:9-58
    is also present at [com.exponea.sdk:sdk:3.1.0] AndroidManifest.xml:14:9-70 value=(@xml/exponea_default_backup_rules).
    Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:6:5-14:19 to override.)

Apparently, our backup rules cannot be merged with com.exponea.sdk:sdk AndroidManifest backup rules. Do you have any suggestions how to fix the issue? It is a  sufficient solution to manually merge these files and add tools:replace="android:fullBackupContent". My proposed solution is to add to our existing rules the exclusion of exponea push token ( "exclude domain="sharedpref" path="EXPONEA_PUSH_TOKEN.xml"" ). Something along the lines of this similar issue https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/9#issuecomment-760150089

**Comment by adam1929** [comment]
Hi @PeterCvopa you are on correct path.
Unfortunately, AndroidManifest::application may hold only single autobackup.xml. Therefore your thinking of tools:replace is correct way to fix this BUT please consider to copy rules from `exponea_default_backup_rules`
New backup rules has been added due to stored PushToken in SharedPrefs. SDK needs to store token in local storage to survive app kill/restart, but PushToken should not be restored after App reinstall (new PushToken will be delivered so restored push token is already invalid and may lead to unpredicted issues)
There is different solution and that is an implementation of customised BackupManager (or other related classes) that may be used to manage SDK backup and backup of your application but it may increase complexity of your app.
