### ISSUE TITLE
How to disable sdk at runtime?

### ISSUE THREAD

**Issue by ursusursus** [exponea/exponea-android-sdk#55]
Hi, I'm working on adding explicit tracking consents to an app and would like some clarification as what to do when consent was removed by user.

If the sdk was not yet initialized, I simply don't initialize it and therefore nothing is tracked

However, if the sdk was initialized, as there is no "deinitialize" method, what's everything I need to disable to make the sdk not track anything (without restarting the app process)?

So far I have just `Exponea.automaticSessionTracking = false`

Anything else?

**Comment by janwelocampo** [comment]
I am facing the same issue with sdk cannot be edited on runtime. + 1 for this

**Comment by ursusursus** [comment]
Yes we ask for consent as a first step. However, should be able to revoke this later (if the consent was given at the first step). As you noted, same for notifications etc

**Comment by adam1929** [comment]
That feature I mentioned is exactly for your case.
If you send a Push notification, it has to contains "tracking consent" flag. Please check documentations due to behaviour and flags. For example, you may define a new consent. If you send a Push notification for customer who didn't have that consent, events for push notifications are not tracked (also InApps etc).
You may use force-track for Push action URL - this will be tracked for non-consent customer also.
And anytime when customer changed his/her decision, you may update this decision in customers profile on Bloomreach app side. Then push notification will be tracked/not-tracked according to this decision.
Please if you have some idea of use-case, feel free to share it with us.
Thank you.

**Comment by adam1929** [comment]
Still, SDK has no option to be reconfigured in runtime. Nor "turned off".
