### ISSUE TITLE
Doesn't call onNewIntent

### ISSUE THREAD

**Issue by kostyanchikoff** [exponea/exponea-android-sdk#64]
Tell me how can I open the Activity (android) notification from the push and call onNewIntent? What is written in the documentation does not work.

**Comment by adam1929** [comment]
Hi @kostyanchikoff thank you for reporting. I assume that you are using `Exponea.handleRemoteMessage` while receiving PushNotification. All is handled by SDK.
As you can see in this github code, SDK is preparing Notification for system and then system handles Application and Activity lifecycle itself. So if you click on Notification (or action) then system will opens your Activity according your AndroidManifest.xml configuration and rules defined by Google.
Our documentation is mentioning `onNewIntent` as warning for cases, that you defines Activity to be able to handle deeplinks/universalLinks and it has to be updated rather than newly created.
In this case (Activity should be updated rather than re-created), you first click will trigger onCreate() method in activity; then second click (and activity is still existing) will trigger onNewIntent().
In case that your activity is configured to re-create always (for example using 'android:launchMode="singleTask"') then your first and second click will trigger onCreate() method in activity !!! but keep in mind that second click results of killing first instance of Activity and creating a new instance of activity. So any private field, runtime state or anything is going to be removed as well.
There is [comprehensive configuration doc](https://developer.android.com/guide/components/activities/tasks-and-back-stack) about Activity lifecycle with multiple ways to achieve your goals
