### ISSUE TITLE
Better way to initialise an AuthorizationProvider class?

### ISSUE THREAD

**Issue by RupW** [exponea/exponea-android-sdk#66]
We're implementing [Customer Token Authorization](https://github.com/exponea/exponea-android-sdk/blob/develop/Documentation/AUTHORIZATION.md#customer-token-authorization).

There's currently no way to pass state into our AuthorizationProvider class: it's created by reflection from config XML, and not even passed a Context to work with. We need access to at least our EncryptedSharedPreferences instance and network classes to fetch new tokens as they expire.

There are ideas [here on StackOverflow](https://stackoverflow.com/q/2002288/243245) how to get state from no starting point by e.g.

* statics on the application class - but Android Studio warns against this as a potential memory leak
* reflection - but this feels fragile

(The memory leak warning might be ignorable since the application class should last the lifetime of the app, but it doesn't feel very clean.)

Could we please have a better interface to build or initialise our AuthorizationProvider object, e.g. pass in a complete object to the SDK init call? Thanks!

**Comment by adam1929** [comment]
Hi @RupW
you may and should use Singleton architecture for AuthorizationProvider, therefore you can kept it as static instance. I cannot see any problem with that.
It is also common pattern to keep Application instance (is technically Application context) as static singleton - Android Studio may mark it as warn because of memory leaks, but if application is killed, there is no way that this static field will stay in memory, so memory leak is not possible for this scenario.
Please check implementation of [CustomerStorage](https://github.com/exponea/exponea-android-sdk/blob/develop/app/src/main/java/com/exponea/example/managers/CustomerTokenStorage.kt) that is also using SharedPreferences so Context is needed. You may "just" replace them by EncryptedSharedPreferences.
